dependencies:
- name: app-template
  version: ~1.2
  repository: https://registry.manage.cloud.qlean.ru/chartrepo/gitlab
  alias: app-template

- name: postgresql
  version: 8.5.0
  repository: https://kubernetes-charts.storage.googleapis.com
  condition: postgresql.enabled
  alias: postgresql
