# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: contractor.proto for package 'sso'

require 'grpc'
require_relative 'contractor_pb'

module Hrm
  module Core
    module ContractorService
      class Service

        include GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'hrm.core.ContractorService'

        rpc :Create, ContractorCreateRequest, ContractorResponse
        rpc :Update, ContractorUpdateRequest, ContractorResponse
        rpc :Search, ContractorSearchRequest, ContractorSearchResponse
        rpc :Block, ContractorBlockRequest, ContractorResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
