# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/contract.proto

require 'google/protobuf'

require_relative '../node_modules/@qlean/nestjs-typeorm-persistence-search/proto/common-search_pb'
require_relative 'product_pb'
require_relative 'specialization_pb'
require_relative 'contractor_pb'
require_relative 'reason_pb'
require_relative 'skill_pb'
require_relative 'common_pb'
require_relative 'wage_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("proto/contract.proto", :syntax => :proto3) do
    add_message "hrm.core.ContractBlockRequest" do
      optional :id, :string, 1
      optional :reason, :message, 2, "hrm.core.BlockingReasonRelation"
      optional :startBlockDate, :string, 3
      optional :endBlockDate, :string, 4
    end
    add_message "hrm.core.ContractCreateRequest" do
      optional :grade, :message, 1, "hrm.core.GradeRelation"
      optional :wage, :message, 2, "hrm.core.WageRelation"
      optional :contractor, :message, 3, "hrm.core.ContractorRelation"
      repeated :skills, :message, 4, "hrm.core.SkillRelation"
    end
    add_message "hrm.core.ContractUpdateRequest" do
      optional :id, :string, 1
      optional :grade, :message, 2, "hrm.core.GradeRelation"
      optional :wage, :message, 3, "hrm.core.WageRelation"
      optional :contractor, :message, 4, "hrm.core.ContractorRelation"
      repeated :skills, :message, 5, "hrm.core.SkillRelation"
    end
    add_message "hrm.core.Contract" do
      optional :id, :string, 1
      optional :createdAt, :string, 2
      optional :updatedAt, :string, 3
      optional :isDeleted, :bool, 4
      optional :deletedAt, :string, 5
      optional :status, :string, 6
      optional :product, :message, 7, "hrm.core.ProductRelation"
      optional :specialization, :message, 8, "hrm.core.SpecializationRelation"
      optional :grade, :message, 9, "hrm.core.Grade"
      optional :wage, :message, 10, "hrm.core.WageRelation"
      optional :contractor, :message, 11, "hrm.core.ContractorRelation"
      repeated :skills, :message, 12, "hrm.core.SkillRelation"
    end
    add_message "hrm.core.ContractResponse" do
      optional :data, :message, 1, "hrm.core.Contract"
    end
    add_message "hrm.core.ContractSearchRequest" do
      optional :page, :int32, 1
      optional :limit, :int32, 2
      repeated :sort, :message, 3, "qlean.common.search.SortField"
      repeated :where, :message, 4, "hrm.core.ContractSearchRequest.WhereFields"
    end
    add_message "hrm.core.ContractSearchRequest.WhereFields" do
      optional :id, :message, 1, "qlean.common.search.UuidCondition"
      optional :status, :message, 2, "qlean.common.search.StringCondition"
      optional :productId, :message, 3, "qlean.common.search.UuidCondition"
      optional :isDeleted, :bool, 4
      optional :specializationId, :message, 5, "qlean.common.search.UuidCondition"
      optional :gradeId, :message, 6, "qlean.common.search.UuidCondition"
      optional :wageId, :message, 7, "qlean.common.search.UuidCondition"
      optional :contractorId, :message, 8, "qlean.common.search.UuidCondition"
    end
    add_message "hrm.core.ContractSearchResponse" do
      repeated :data, :message, 1, "hrm.core.Contract"
      optional :page, :int32, 2
      optional :pageCount, :int32, 3
      optional :limit, :int32, 4
      optional :count, :int32, 5
      optional :total, :int32, 6
    end
    add_message "hrm.core.ContractRelation" do
      optional :id, :string, 1
    end
  end
end

module Hrm
  module Core
    ContractBlockRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.ContractBlockRequest").msgclass
    ContractCreateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.ContractCreateRequest").msgclass
    ContractUpdateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.ContractUpdateRequest").msgclass
    Contract = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.Contract").msgclass
    ContractResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.ContractResponse").msgclass
    ContractSearchRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.ContractSearchRequest").msgclass
    ContractSearchRequest::WhereFields = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.ContractSearchRequest.WhereFields").msgclass
    ContractSearchResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.ContractSearchResponse").msgclass
    ContractRelation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.ContractRelation").msgclass
  end
end
