# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: contract.proto for package 'sso'

require 'grpc'
require_relative 'contract_pb'

module Hrm
  module Core
    module ContractService
      class Service

        include GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'hrm.core.ContractService'

        rpc :Create, ContractCreateRequest, ContractResponse
        rpc :Update, ContractUpdateRequest, ContractResponse
        rpc :Search, ContractorSearchRequest, ContractSearchResponse
        rpc :Block, ContractBlockRequest, ContractResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
