# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/position.proto

require 'google/protobuf'

require_relative '../node_modules/@qlean/nestjs-typeorm-persistence-search/proto/common-search_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("proto/position.proto", :syntax => :proto3) do
    add_message "hrm.core.PositionCreateRequest" do
      optional :title, :string, 1
      optional :name, :string, 2
    end
    add_message "hrm.core.PositionUpdateRequest" do
      optional :id, :string, 1
      optional :title, :string, 2
      optional :name, :string, 3
    end
    add_message "hrm.core.PositionResponse" do
      optional :data, :message, 1, "hrm.core.Position"
    end
    add_message "hrm.core.PositionSearchRequest" do
      optional :page, :int32, 1
      optional :limit, :int32, 2
      repeated :sort, :message, 3, "qlean.common.search.SortField"
      repeated :where, :message, 4, "hrm.core.PositionSearchRequest.WhereFields"
    end
    add_message "hrm.core.PositionSearchRequest.WhereFields" do
      optional :id, :message, 1, "qlean.common.search.UuidCondition"
      optional :title, :message, 2, "qlean.common.search.StringCondition"
      optional :name, :message, 3, "qlean.common.search.StringCondition"
      optional :isDeleted, :bool, 4
      optional :createdAt, :message, 5, "qlean.common.search.DateCondition"
      optional :updatedAt, :message, 6, "qlean.common.search.DateCondition"
      optional :deletedAt, :message, 7, "qlean.common.search.DateCondition"
    end
    add_message "hrm.core.PositionSearchResponse" do
      repeated :data, :message, 1, "hrm.core.Position"
      optional :page, :int32, 2
      optional :pageCount, :int32, 3
      optional :limit, :int32, 4
      optional :count, :int32, 5
      optional :total, :int32, 6
    end
    add_message "hrm.core.Position" do
      optional :id, :string, 1
      optional :title, :string, 2
      optional :name, :string, 3
      optional :createdAt, :string, 4
      optional :updatedAt, :string, 5
      optional :isDeleted, :bool, 6
      optional :deletedAt, :string, 7
    end
    add_message "hrm.core.PositionRelation" do
      optional :id, :string, 1
      optional :title, :string, 2
      optional :name, :string, 3
    end
  end
end

module Hrm
  module Core
    PositionCreateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.PositionCreateRequest").msgclass
    PositionUpdateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.PositionUpdateRequest").msgclass
    PositionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.PositionResponse").msgclass
    PositionSearchRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.PositionSearchRequest").msgclass
    PositionSearchRequest::WhereFields = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.PositionSearchRequest.WhereFields").msgclass
    PositionSearchResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.PositionSearchResponse").msgclass
    Position = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.Position").msgclass
    PositionRelation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.PositionRelation").msgclass
  end
end
