# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/product.proto

require 'google/protobuf'

require_relative '../node_modules/@qlean/nestjs-typeorm-persistence-search/proto/common-search_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("proto/product.proto", :syntax => :proto3) do
    add_message "hrm.core.ProductCreateRequest" do
      optional :title, :string, 1
      optional :name, :string, 2
    end
    add_message "hrm.core.ProductUpdateRequest" do
      optional :id, :string, 1
      optional :title, :string, 2
      optional :name, :string, 3
    end
    add_message "hrm.core.ProductResponse" do
      optional :data, :message, 1, "hrm.core.Product"
    end
    add_message "hrm.core.ProductSearchRequest" do
      optional :page, :int32, 1
      optional :limit, :int32, 2
      repeated :sort, :message, 3, "qlean.common.search.SortField"
      repeated :where, :message, 4, "hrm.core.ProductSearchRequest.WhereFields"
    end
    add_message "hrm.core.ProductSearchRequest.WhereFields" do
      optional :id, :message, 1, "qlean.common.search.UuidCondition"
      optional :title, :message, 2, "qlean.common.search.StringCondition"
      optional :name, :message, 3, "qlean.common.search.StringCondition"
      optional :isDeleted, :bool, 4
      optional :createdAt, :message, 5, "qlean.common.search.DateCondition"
      optional :updatedAt, :message, 6, "qlean.common.search.DateCondition"
      optional :deletedAt, :message, 7, "qlean.common.search.DateCondition"
    end
    add_message "hrm.core.ProductSearchResponse" do
      repeated :data, :message, 1, "hrm.core.Product"
      optional :page, :int32, 2
      optional :pageCount, :int32, 3
      optional :limit, :int32, 4
      optional :count, :int32, 5
      optional :total, :int32, 6
    end
    add_message "hrm.core.Product" do
      optional :id, :string, 1
      optional :title, :string, 2
      optional :name, :string, 3
      optional :createdAt, :string, 4
      optional :updatedAt, :string, 5
      optional :isDeleted, :bool, 6
      optional :deletedAt, :string, 7
    end
    add_message "hrm.core.ProductRelation" do
      optional :id, :string, 1
      optional :title, :string, 2
      optional :name, :string, 3
    end
  end
end

module Hrm
  module Core
    ProductCreateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.ProductCreateRequest").msgclass
    ProductUpdateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.ProductUpdateRequest").msgclass
    ProductResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.ProductResponse").msgclass
    ProductSearchRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.ProductSearchRequest").msgclass
    ProductSearchRequest::WhereFields = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.ProductSearchRequest.WhereFields").msgclass
    ProductSearchResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.ProductSearchResponse").msgclass
    Product = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.Product").msgclass
    ProductRelation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.ProductRelation").msgclass
  end
end
