# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/reason-group.proto

require 'google/protobuf'

require_relative '../node_modules/@qlean/nestjs-typeorm-persistence-search/proto/common-search_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("proto/reason-group.proto", :syntax => :proto3) do
    add_message "hrm.core.BlockingReasonGroupCreateRequest" do
      optional :name, :string, 1
    end
    add_message "hrm.core.BlockingReasonGroupUpdateRequest" do
      optional :id, :string, 1
      optional :name, :string, 2
    end
    add_message "hrm.core.BlockingReasonGroupResponse" do
      optional :data, :message, 1, "hrm.core.BlockingReasonGroup"
    end
    add_message "hrm.core.BlockingReasonGroupSearchRequest" do
      optional :page, :int32, 1
      optional :limit, :int32, 2
      repeated :sort, :message, 3, "qlean.common.search.SortField"
      repeated :where, :message, 4, "hrm.core.BlockingReasonGroupSearchRequest.WhereFields"
    end
    add_message "hrm.core.BlockingReasonGroupSearchRequest.WhereFields" do
      optional :id, :message, 1, "qlean.common.search.UuidCondition"
      optional :name, :message, 2, "qlean.common.search.StringCondition"
    end
    add_message "hrm.core.BlockingReasonGroupSearchResponse" do
      repeated :data, :message, 1, "hrm.core.BlockingReasonGroup"
      optional :page, :int32, 2
      optional :pageCount, :int32, 3
      optional :limit, :int32, 4
      optional :count, :int32, 5
      optional :total, :int32, 6
    end
    add_message "hrm.core.BlockingReasonGroup" do
      optional :id, :string, 1
      optional :name, :string, 2
      optional :createdAt, :string, 3
      optional :updatedAt, :string, 4
      optional :isDeleted, :bool, 5
      optional :deletedAt, :string, 6
    end
    add_message "hrm.core.BlockingReasonGroupRelation" do
      optional :id, :string, 1
      optional :name, :string, 2
    end
  end
end

module Hrm
  module Core
    BlockingReasonGroupCreateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.BlockingReasonGroupCreateRequest").msgclass
    BlockingReasonGroupUpdateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.BlockingReasonGroupUpdateRequest").msgclass
    BlockingReasonGroupResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.BlockingReasonGroupResponse").msgclass
    BlockingReasonGroupSearchRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.BlockingReasonGroupSearchRequest").msgclass
    BlockingReasonGroupSearchRequest::WhereFields = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.BlockingReasonGroupSearchRequest.WhereFields").msgclass
    BlockingReasonGroupSearchResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.BlockingReasonGroupSearchResponse").msgclass
    BlockingReasonGroup = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.BlockingReasonGroup").msgclass
    BlockingReasonGroupRelation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.BlockingReasonGroupRelation").msgclass
  end
end
