# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/reason.proto

require 'google/protobuf'

require_relative '../node_modules/@qlean/nestjs-typeorm-persistence-search/proto/common-search_pb'
require_relative 'reason-group_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("proto/reason.proto", :syntax => :proto3) do
    add_message "hrm.core.BlockingReasonResponse" do
      optional :data, :message, 1, "hrm.core.BlockingReason"
    end
    add_message "hrm.core.BlockingReasonSearchRequest" do
      optional :page, :int32, 1
      optional :limit, :int32, 2
      repeated :sort, :message, 3, "qlean.common.search.SortField"
      repeated :where, :message, 4, "hrm.core.BlockingReasonSearchRequest.WhereFields"
    end
    add_message "hrm.core.BlockingReasonSearchRequest.WhereFields" do
      optional :id, :message, 1, "qlean.common.search.UuidCondition"
      optional :isDeleted, :bool, 2
      optional :type, :message, 3, "qlean.common.search.StringCondition"
      optional :isRecoverable, :bool, 4
      optional :isAvailableForContractor, :bool, 5
      optional :isInstant, :bool, 6
      optional :isNeedRetraining, :bool, 7
      optional :isCommonBlock, :bool, 8
    end
    add_message "hrm.core.BlockingReasonSearchResponse" do
      repeated :data, :message, 1, "hrm.core.BlockingReason"
      optional :page, :int32, 2
      optional :limit, :int32, 3
      optional :pageCount, :int32, 4
      optional :count, :int32, 5
      optional :total, :int32, 6
    end
    add_message "hrm.core.BlockingReasonCreateRequest" do
      optional :name, :string, 1
      optional :type, :string, 2
      optional :isAvailableForContractor, :bool, 3
      optional :isInstant, :bool, 4
      optional :isNeedRetraining, :bool, 5
      optional :isCommonBlock, :bool, 6
      optional :isRecoverable, :bool, 7
      optional :group, :message, 8, "hrm.core.BlockingReasonGroupRelation"
    end
    add_message "hrm.core.BlockingReasonUpdateRequest" do
      optional :id, :string, 1
      optional :name, :string, 2
      optional :type, :string, 3
      optional :isAvailableForContractor, :bool, 4
      optional :isInstant, :bool, 5
      optional :isNeedRetraining, :bool, 6
      optional :isCommonBlock, :bool, 7
      optional :isRecoverable, :bool, 8
      optional :group, :message, 9, "hrm.core.BlockingReasonGroupRelation"
    end
    add_message "hrm.core.BlockingReason" do
      optional :id, :string, 1
      optional :name, :string, 2
      optional :type, :string, 3
      optional :isAvailableForContractor, :bool, 4
      optional :isInstant, :bool, 5
      optional :isNeedRetraining, :bool, 6
      optional :isCommonBlock, :bool, 7
      optional :isRecoverable, :bool, 8
      optional :group, :message, 9, "hrm.core.BlockingReasonGroupRelation"
      optional :createdAt, :string, 10
      optional :updatedAt, :string, 11
      optional :isDeleted, :bool, 12
      optional :deletedAt, :string, 13
    end
    add_message "hrm.core.BlockingReasonRelation" do
      optional :id, :string, 1
      optional :name, :string, 2
      optional :type, :string, 3
    end
  end
end

module Hrm
  module Core
    BlockingReasonResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.BlockingReasonResponse").msgclass
    BlockingReasonSearchRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.BlockingReasonSearchRequest").msgclass
    BlockingReasonSearchRequest::WhereFields = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.BlockingReasonSearchRequest.WhereFields").msgclass
    BlockingReasonSearchResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.BlockingReasonSearchResponse").msgclass
    BlockingReasonCreateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.BlockingReasonCreateRequest").msgclass
    BlockingReasonUpdateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.BlockingReasonUpdateRequest").msgclass
    BlockingReason = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.BlockingReason").msgclass
    BlockingReasonRelation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.BlockingReasonRelation").msgclass
  end
end
