# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/skill.proto

require 'google/protobuf'

require_relative '../node_modules/@qlean/nestjs-typeorm-persistence-search/proto/common-search_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("proto/skill.proto", :syntax => :proto3) do
    add_message "hrm.core.SkillCreateRequest" do
      optional :title, :string, 1
      optional :name, :string, 2
      repeated :option, :string, 3
    end
    add_message "hrm.core.SkillUpdateRequest" do
      optional :id, :string, 1
      optional :title, :string, 2
      optional :name, :string, 3
      repeated :option, :string, 4
    end
    add_message "hrm.core.SkillResponse" do
      optional :data, :message, 1, "hrm.core.Skill"
    end
    add_message "hrm.core.SkillSearchRequest" do
      optional :page, :int32, 1
      optional :limit, :int32, 2
      repeated :sort, :message, 3, "qlean.common.search.SortField"
      repeated :where, :message, 4, "hrm.core.SkillSearchRequest.WhereFields"
    end
    add_message "hrm.core.SkillSearchRequest.WhereFields" do
      optional :id, :message, 1, "qlean.common.search.UuidCondition"
      optional :title, :message, 2, "qlean.common.search.StringCondition"
      optional :name, :message, 3, "qlean.common.search.StringCondition"
      optional :isDeleted, :bool, 4
      optional :createdAt, :message, 5, "qlean.common.search.DateCondition"
      optional :updatedAt, :message, 6, "qlean.common.search.DateCondition"
      optional :deletedAt, :message, 7, "qlean.common.search.DateCondition"
      optional :option, :message, 8, "qlean.common.search.StringCondition"
    end
    add_message "hrm.core.SkillSearchResponse" do
      repeated :data, :message, 1, "hrm.core.Skill"
      optional :page, :int32, 2
      optional :pageCount, :int32, 3
      optional :limit, :int32, 4
      optional :count, :int32, 5
      optional :total, :int32, 6
    end
    add_message "hrm.core.Skill" do
      optional :id, :string, 1
      optional :title, :string, 2
      optional :name, :string, 3
      repeated :option, :string, 4
      optional :createdAt, :string, 5
      optional :updatedAt, :string, 6
      optional :isDeleted, :bool, 7
      optional :deletedAt, :string, 8
    end
    add_message "hrm.core.SkillRelation" do
      optional :id, :string, 1
      optional :title, :string, 2
      optional :name, :string, 3
      repeated :option, :string, 4
    end
  end
end

module Hrm
  module Core
    SkillCreateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.SkillCreateRequest").msgclass
    SkillUpdateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.SkillUpdateRequest").msgclass
    SkillResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.SkillResponse").msgclass
    SkillSearchRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.SkillSearchRequest").msgclass
    SkillSearchRequest::WhereFields = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.SkillSearchRequest.WhereFields").msgclass
    SkillSearchResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.SkillSearchResponse").msgclass
    Skill = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.Skill").msgclass
    SkillRelation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.SkillRelation").msgclass
  end
end
