# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/specialization.proto

require 'google/protobuf'

require_relative '../node_modules/@qlean/nestjs-typeorm-persistence-search/proto/common-search_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("proto/specialization.proto", :syntax => :proto3) do
    add_message "hrm.core.SpecializationCreateRequest" do
      optional :title, :string, 1
      optional :name, :string, 2
    end
    add_message "hrm.core.SpecializationUpdateRequest" do
      optional :id, :string, 1
      optional :title, :string, 2
      optional :name, :string, 3
    end
    add_message "hrm.core.SpecializationResponse" do
      optional :data, :message, 1, "hrm.core.Specialization"
    end
    add_message "hrm.core.SpecializationSearchRequest" do
      optional :page, :int32, 1
      optional :limit, :int32, 2
      repeated :sort, :message, 3, "qlean.common.search.SortField"
      repeated :where, :message, 4, "hrm.core.SpecializationSearchRequest.WhereFields"
    end
    add_message "hrm.core.SpecializationSearchRequest.WhereFields" do
      optional :id, :message, 1, "qlean.common.search.UuidCondition"
      optional :title, :message, 2, "qlean.common.search.StringCondition"
      optional :name, :message, 3, "qlean.common.search.StringCondition"
      optional :isDeleted, :bool, 4
      optional :createdAt, :message, 5, "qlean.common.search.DateCondition"
      optional :updatedAt, :message, 6, "qlean.common.search.DateCondition"
      optional :deletedAt, :message, 7, "qlean.common.search.DateCondition"
    end
    add_message "hrm.core.SpecializationSearchResponse" do
      repeated :data, :message, 1, "hrm.core.Specialization"
      optional :page, :int32, 2
      optional :pageCount, :int32, 3
      optional :limit, :int32, 4
      optional :count, :int32, 5
      optional :total, :int32, 6
    end
    add_message "hrm.core.Specialization" do
      optional :id, :string, 1
      optional :title, :string, 2
      optional :name, :string, 3
      optional :createdAt, :string, 4
      optional :updatedAt, :string, 5
      optional :isDeleted, :bool, 6
      optional :deletedAt, :string, 7
    end
    add_message "hrm.core.SpecializationRelation" do
      optional :id, :string, 1
      optional :title, :string, 2
      optional :name, :string, 3
    end
  end
end

module Hrm
  module Core
    SpecializationCreateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.SpecializationCreateRequest").msgclass
    SpecializationUpdateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.SpecializationUpdateRequest").msgclass
    SpecializationResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.SpecializationResponse").msgclass
    SpecializationSearchRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.SpecializationSearchRequest").msgclass
    SpecializationSearchRequest::WhereFields = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.SpecializationSearchRequest.WhereFields").msgclass
    SpecializationSearchResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.SpecializationSearchResponse").msgclass
    Specialization = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.Specialization").msgclass
    SpecializationRelation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.SpecializationRelation").msgclass
  end
end
