# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/wage.proto

require 'google/protobuf'

require_relative '../node_modules/@qlean/nestjs-typeorm-persistence-search/proto/common-search_pb'
require_relative 'specialization_pb'
require_relative 'product_pb'
require_relative 'common_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("proto/wage.proto", :syntax => :proto3) do
    add_message "hrm.core.WageCreateRequest" do
      optional :name, :string, 1
      optional :product, :message, 2, "hrm.core.ProductRelation"
      optional :specialization, :message, 3, "hrm.core.SpecializationRelation"
      repeated :grades, :message, 4, "hrm.core.Grade"
      optional :regionId, :string, 5
      optional :type, :string, 6
    end
    add_message "hrm.core.WageUpdateRequest" do
      optional :id, :string, 1
      optional :name, :string, 2
      optional :product, :message, 3, "hrm.core.ProductRelation"
      optional :specialization, :message, 4, "hrm.core.SpecializationRelation"
      repeated :grades, :message, 5, "hrm.core.Grade"
      optional :regionId, :string, 6
      optional :type, :string, 7
    end
    add_message "hrm.core.WageResponse" do
      optional :data, :message, 1, "hrm.core.Wage"
    end
    add_message "hrm.core.WageSearchRequest" do
      optional :page, :int32, 1
      optional :limit, :int32, 2
      repeated :sort, :message, 3, "qlean.common.search.SortField"
      repeated :where, :message, 4, "hrm.core.WageSearchRequest.WhereFields"
    end
    add_message "hrm.core.WageSearchRequest.WhereFields" do
      optional :id, :message, 1, "qlean.common.search.UuidCondition"
      optional :createdAt, :message, 2, "qlean.common.search.DateCondition"
      optional :updatedAt, :message, 3, "qlean.common.search.DateCondition"
      optional :deletedAt, :message, 4, "qlean.common.search.DateCondition"
      optional :isDeleted, :bool, 5
      optional :name, :message, 6, "qlean.common.search.StringCondition"
      optional :productId, :message, 7, "qlean.common.search.UuidCondition"
      optional :specializationId, :message, 8, "qlean.common.search.UuidCondition"
      optional :regionId, :message, 9, "qlean.common.search.UuidCondition"
    end
    add_message "hrm.core.WageSearchResponse" do
      repeated :data, :message, 1, "hrm.core.Wage"
      optional :page, :int32, 2
      optional :pageCount, :int32, 3
      optional :limit, :int32, 4
      optional :count, :int32, 5
      optional :total, :int32, 6
    end
    add_message "hrm.core.Wage" do
      optional :id, :string, 1
      optional :createdAt, :string, 2
      optional :updatedAt, :string, 3
      optional :isDeleted, :bool, 4
      optional :deletedAt, :string, 5
      optional :name, :string, 6
      optional :product, :message, 7, "hrm.core.Product"
      optional :specialization, :message, 8, "hrm.core.SpecializationRelation"
      repeated :grades, :message, 9, "hrm.core.Grade"
      optional :regionId, :string, 10
      optional :type, :string, 11
    end
    add_message "hrm.core.WageRelation" do
      optional :id, :string, 1
      optional :name, :string, 2
    end
  end
end

module Hrm
  module Core
    WageCreateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.WageCreateRequest").msgclass
    WageUpdateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.WageUpdateRequest").msgclass
    WageResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.WageResponse").msgclass
    WageSearchRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.WageSearchRequest").msgclass
    WageSearchRequest::WhereFields = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.WageSearchRequest.WhereFields").msgclass
    WageSearchResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.WageSearchResponse").msgclass
    Wage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.Wage").msgclass
    WageRelation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hrm.core.WageRelation").msgclass
  end
end
